services:
  - type: web
    name: haltter
    env: python
    region: oregon  
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        sync: true

databases:
  - name: Data1
    plan: free
    region: oregon
    databaseName: Data1
    ipAllowList: []

envVarGroups:
  - name: myappenv
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Data1
          property: connectionString